version: '3.7'
services:
  default_db:
    image: postgres:12.6
    volumes:
      - default_data:/var/lib/postgresql/data
    environment:
      # Authorize insecure connections;
      # used only in local development.
      POSTGRES_HOST_AUTH_METHOD: trust
      # Reference: <https://www.postgresql.org/docs/12/auth-trust.html>
    networks:
      - backend

  internal_db:
    image: postgres:12.6
    volumes:
      - internal_data:/var/lib/postgresql/data
    environment:
      # Authorize insecure connections;
      # used only in local development.
      POSTGRES_HOST_AUTH_METHOD: trust
      # Reference: <https://www.postgresql.org/docs/12/auth-trust.html>
    networks:
      - backend

  web:
    build: .
    init: true
    volumes:
      - .:/app
    environment:
      PORT: 8000
      DJANGO_ENV: development
      DJANGO_SECRET_KEY: supersecretkey
    ports:
      - "8000:8000"
    depends_on:
      - default_db
      - internal_db
    networks:
      - backend


volumes:
  default_data:
    driver: local
  internal_data:
    driver: local


networks:
  backend:
